version: '3.1'

services:
  db:
    image: mysql:8.0.34-debian
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2
volumes:
  dbdata: 
    driver: local
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

    