version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=my-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s http://elasticsearch:9200/_cluster/health?pretty | grep -q -e 'green' -e 'yellow'
      interval: 10s
      timeout: 10s
      retries: 50


  kibana:
    container_name: kibana
    image: kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    healthcheck:
     test: curl -s -I  http://kibana:5601/app/home | grep -q 'HTTP/1.1 200 OK'
     interval: 10s
     timeout: 10s
     retries: 50  
    depends_on:
      elasticsearch:
        condition: service_healthy
 

  logstash:
    container_name: logstash
    image: logstash:7.17.9
    volumes:
     - logstash-data:/usr/share/logstash/data
     - "/projects/test/ingest_data/:/usr/share/logstash/ingest_data/:ro"
     - "/projects/test/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
    environment:
     - xpack.monitoring.enabled=false
     - ELASTIC_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy


  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.17.9
    user: root
    volumes:
      - metricbeat-data:/usr/share/metricbeat/data
      - "/projects/test/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    environment:
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - KIBANA_HOSTS=http://kibana:5601
      - LOGSTASH_HOSTS=http://logstash:9600
      - FILEBEAT_HOSTS=http://filebeat:5066
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy


  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.17.9
    command: --strict.perms=false
    user: root
    volumes:
      - /projects/test/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - filebeat-data:/usr/share/filebeat/data
      - "/projects/test/fb-nginx.yml:/usr/share/filebeat/modules.d/fb-nginx.yml:ro"
      - "/projects/test/ingest_data/:/usr/share/filebeat/ingest_data/:ro"
    environment:
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - KIBANA_HOSTS=http://kibana:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy


  nginx:
    container_name: nginx
    image: nginx:1.24.0
    volumes:
      - /projects/test/ingest_data/:/var/log/nginx/
    ports:
      - 80:80
      - 8080:8080


volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  metricbeat-data:
    driver: local
  logstash-data:
    driver: local
  filebeat-data:
    driver: local